<?php

namespace fredi\AppBundle\Repository;

/**
 * AssociationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationUserRepository extends \Doctrine\ORM\EntityRepository
{
}
