<?php

namespace fredi\AppBundle\Repository;

/**
 * CostUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostUserRepository extends \Doctrine\ORM\EntityRepository
{
}
