<?php

namespace fredi\AppBundle\Repository;

/**
 * CostLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostLineRepository extends \Doctrine\ORM\EntityRepository
{
}
