<?php

namespace fredi\AppBundle\Repository;

/**
 * ReservationLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationLineRepository extends \Doctrine\ORM\EntityRepository
{
}
