<?php

namespace fredi\AppBundle\Repository;

/**
 * UserReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
